// import { createSlice } from '@reduxjs/toolkit';

// // Define the initial state for the counter
// const initialState = {
//   value: 0,
// };

// // Create a slice of the store
// const counterSlice = createSlice({
//   name: 'counter',
//   initialState,
//   reducers: {
//     increment: (state) => {
//       state.value += 1; // Increment the counter value
//     },
//     decrement: (state) => {
//       state.value -= 1; // Decrement the counter value
//     },
//     incrementByAmount: (state, action) => {
//       state.value += action.payload; // Increment by a specific amount
//     },
//   },
// });

// // Export actions generated by the slice
// export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// // Export the reducer to be used in the store
// export default counterSlice.reducer;
